  # Database connection configuration
  spring:
    datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/golf?createDatabaseIfNotExist=true
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:1234567890}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: vanthanh1810xx@gmail.com
      password: odqe asxq ysai eecp
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
    web:
      resources:
        static-locations: classpath:/static/

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 1075279700700-tu1io4ed8t550tiaj0acdmp3ejm8ggkf.apps.googleusercontent.com
              client-secret: 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
              redirect-uri: "http://localhost:8080/login/oauth2/code/google"
              scope:
                - email
                - profile


  payment:
    vnPay:
      url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
      tmnCode: "B392S5MZ"
      secretKey: "GIGCQNW0JPP8IW4OM6CURR1M8R1EAUZ7"
      returnUrl: "http://localhost:3000/vnpay-return"
      version: "2.1.0"
      command: "pay"
      orderType: "other"

  jwt:
    secret: "d83hfsdfsfdfs9e32r23fwfshfsdhfsdfskjfsdfsd343432sdffsdfdsf"
    expiration: 36000000
    refresh-secret: "d83sfdsdfsdfwrioewfjjjjewrw3246238948nfdsf889fsd89sdf"
    refresh-expiration: 86400000


  upload:
    dir: uploads

  app:
    secretKey: "1234567890abcdef"
    redirect-url: "http://localhost:3000/oauth2/redirect"
